### ISSUE TITLE
 Error connecting to Tractives: Cannot connect to host graph.tractive.com:443 ssl:default [Try again] 

### ISSUE THREAD

**Issue by sineczek** [Danielhiversen/home_assistant_tractive#10]
First of all, thank you for this integration, I waited a long time for it!

Since yesterday I see an error in my logs:

```
2020-10-26 02:24:16 ERROR (MainThread) [custom_components.tractive.device_tracker] Error connecting to Tractives: Cannot connect to host graph.tractive.com:443 ssl:default [Try again] 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 964, in _create_direct_connection
    hosts = await asyncio.shield(self._resolve_host(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 829, in _resolve_host
    addrs = await \
  File "/usr/local/lib/python3.8/site-packages/aiohttp/resolver.py", line 29, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tractive/device_tracker.py", line 145, in _fetch_tracker_data
    resp = await self._session.get(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 971, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host graph.tractive.com:443 ssl:default [Try again]
```

My tractive config:
```
device_tracker:
  - platform: tractive
    username: !secret tractivel
    password: !secret tractivep
```
everything seems to be working fine despite this bug

**Comment by Danielhiversen** [comment]
Probably nothing I can do with this :/
Most be server issues at tractive or networks issue at your hand.
