### ISSUE TITLE
Trackers position is only updated once after hass restart

### ISSUE THREAD

**Issue by michaelhenningersrb** [Danielhiversen/home_assistant_tractive#31]
Hi,

after restarting my hass instance, the tracker is only updated once...
After that, I get the following error:

```
2021-05-05 11:36:01 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform legacy
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 235, in async_setup_legacy
setup = await self.platform.async_setup_scanner(
File "/config/custom_components/tractive/device_tracker.py", line 42, in async_setup_scanner
return await scanner.async_init()
File "/config/custom_components/tractive/device_tracker.py", line 69, in async_init
async_track_time_interval(self.hass, self._async_update, self.scan_interval)
File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1260, in async_track_time_interval
remove = async_track_point_in_utc_time(hass, interval_listener_job, next_interval())
File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1246, in next_interval
return dt_util.utcnow() + interval
TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'int'
```

I'm not an expert in developing custom components. Any ideas?

**Comment by Danielhiversen** [comment]
Could you try to upgrade to 0.2.3?

**Comment by michaelhenningersrb** [comment]
@Danielhiversen It's working! Thank you ;)
